name: Daily Waste Prediction
on:
 workflow_dispatch:
 schedule:
   - cron: "0 4 * * *"  # Runs every day at 4:00 AM UTC
jobs:
 run:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Setup Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.11'
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
     - name: Save FIREBASE_KEY to file
       run: echo "$FIREBASE_KEY" > firebase_key.json
       env:
         FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
     - name: Validate firebase_key.json
       run: python -m json.tool firebase_key.json
     - name: Run prediction
       run: python predict.py