name: Daily Waste Prediction

on:

  schedule:

    - cron: '0 0 * * *'  # Runs daily at midnight UTC

  workflow_dispatch:

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v3

    - name: Setup Python

      uses: actions/setup-python@v4

      with:

        python-version: '3.11'

    - name: Install dependencies

      run: |

        pip install -r requirements.txt

    - name: Save FIREBASE_KEY to file

      run: echo "${{ secrets.FIREBASE_KEY }}" > firebase_key.json

    # ✅ JSON validation step (optional but recommended)

    - name: Validate firebase_key.json

      run: python -m json.tool firebase_key.json

    - name: Run prediction

      run: python predict.py
 